// Test harness for cross-language verification between dubbo-rs and dubbo-java.

use std::fmt::Write as _;
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::time::{Duration, Instant};

// ── Constants ───────────────────────────────────────────────────────────────

/// Root of the workspace (`CARGO_MANIFEST_DIR` of cross-lang-tests)
const WORKSPACE_DIR: &str = env!("CARGO_MANIFEST_DIR");
const FIXTURES_DIR: &str = "../tests/fixtures/hessian2";
const DOCKER_COMPOSE_FILE: &str = "../tests/docker-compose.yml";
const JAVA_FIXTURES_DIR: &str = "../tests/java-fixtures";

// ── FixtureLoader ───────────────────────────────────────────────────────────

/// Loads binary fixture files generated by Java `Hessian2ReferenceEncoder`.
#[derive(Clone, Copy)]
pub struct FixtureLoader;

impl FixtureLoader {
    /// Read a fixture file by category and filename.
    ///
    /// # Panics
    /// Panics if the fixture file does not exist or cannot be read.
    #[must_use]
    pub fn read(category: &str, filename: &str) -> Vec<u8> {
        let path = Self::path(category, filename);
        std::fs::read(&path)
            .unwrap_or_else(|e| panic!("failed to read fixture '{category}/{filename}': {e}"))
    }

    /// Get the full path to a fixture file.
    #[must_use]
    pub fn path(category: &str, filename: &str) -> PathBuf {
        let root = PathBuf::from(WORKSPACE_DIR);
        root.join(FIXTURES_DIR).join(category).join(filename)
    }

    /// Returns the absolute path to the fixture directory root.
    #[must_use]
    pub fn root() -> PathBuf {
        PathBuf::from(WORKSPACE_DIR).join(FIXTURES_DIR)
    }

    /// List all `.bin` files in a category directory.
    ///
    /// # Panics
    /// Panics if the category directory does not exist or cannot be read.
    #[must_use]
    pub fn list(category: &str) -> Vec<String> {
        let dir = Self::root().join(category);
        let mut files: Vec<String> = std::fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("fixture dir '{category}' not found: {e}"))
            .filter_map(|entry| {
                let entry = entry.ok()?;
                let name = entry.file_name().into_string().ok()?;
                #[allow(clippy::case_sensitive_file_extension_comparisons)]
                if name.ends_with(".bin") {
                    Some(name)
                } else {
                    None
                }
            })
            .collect();
        files.sort();
        files
    }
}

// ── PortAllocator ────────────────────────────────────────────────────────────

/// Allocates unique ports for test services.
pub struct PortAllocator;

impl PortAllocator {
    pub const BASE_PORT: u16 = 21000;

    /// Allocate a port by briefly binding to port 0 (OS-assigned).
    ///
    /// This uses `TcpListener::bind("127.0.0.1:0")` to get an OS-assigned
    /// ephemeral port, then immediately releases it. While there is a
    /// theoretical TOCTOU race between release and actual use, the OS
    /// typically cycles through a large ephemeral range (32768–60999 on
    /// Linux), making collisions extremely unlikely in practice.
    ///
    /// For cases where the caller needs to guarantee the port is held until
    /// they bind (e.g. starting a TCP server), use [`allocate_held`] instead.
    ///
    /// # Panics
    /// Panics if unable to bind to an ephemeral port.
    #[must_use]
    pub fn allocate() -> u16 {
        let (listener, port) = Self::allocate_held();
        drop(listener);
        port
    }

    /// Allocate a port and return the bound [`TcpListener`] to hold it.
    ///
    /// The returned listener keeps the port occupied until the caller drops it,
    /// eliminating TOCTOU races. Callers should drop the listener immediately
    /// before binding their own server to the same port.
    ///
    /// # Panics
    /// Panics if unable to bind to an ephemeral port.
    #[must_use]
    pub fn allocate_held() -> (std::net::TcpListener, u16) {
        let listener =
            TcpListener::bind("127.0.0.1:0").expect("PortAllocator: failed to bind ephemeral port");
        let port = listener.local_addr().unwrap().port();
        (listener, port)
    }

    /// Check if a port is available on localhost.
    #[must_use]
    pub fn is_port_available(port: u16) -> bool {
        TcpListener::bind(("127.0.0.1", port)).is_ok()
    }

    /// Wait for a port to become unavailable (service started listening),
    /// up to `timeout`.
    #[must_use]
    pub fn wait_for_port(port: u16, timeout: Duration) -> bool {
        let deadline = Instant::now() + timeout;
        while Instant::now() < deadline {
            if !Self::is_port_available(port) {
                return true; // port is now in use
            }
            std::thread::sleep(Duration::from_millis(200));
        }
        false
    }
}

// ── Java process management ─────────────────────────────────────────────────

/// Manages Java test server processes.
pub struct JavaServer {
    child: Option<Child>,
    port: u16,
}

impl JavaServer {
    /// Start a Java `DubboTcpTestServer` on the given port.
    ///
    /// # Errors
    /// Returns an error if the Java process cannot be started.
    pub fn start_dubbo_tcp(port: u16) -> Result<Self, String> {
        let java_dir = PathBuf::from(WORKSPACE_DIR).join(JAVA_FIXTURES_DIR);
        let classpath = Self::build_classpath(&java_dir)?;

        let child = Command::new("java")
            .args([
                "-cp",
                &classpath,
                "com.dubborst.fixtures.DubboTcpTestServer",
                &port.to_string(),
            ])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|e| format!("failed to start DubboTcpTestServer: {e}"))?;

        let ready = PortAllocator::wait_for_port(port, Duration::from_secs(15));
        if !ready {
            return Err(format!(
                "DubboTcpTestServer on port {port} did not start in time"
            ));
        }

        Ok(Self {
            child: Some(child),
            port,
        })
    }

    /// Start a Java `TripleTestServer` on the given port.
    ///
    /// # Errors
    /// Returns an error if the Java process cannot be started.
    pub fn start_triple(port: u16) -> Result<Self, String> {
        let java_dir = PathBuf::from(WORKSPACE_DIR).join(JAVA_FIXTURES_DIR);
        let classpath = Self::build_classpath(&java_dir)?;

        let child = Command::new("java")
            .args([
                "-cp",
                &classpath,
                "com.dubborst.fixtures.TripleTestServer",
                &port.to_string(),
            ])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|e| format!("failed to start TripleTestServer: {e}"))?;

        Ok(Self {
            child: Some(child),
            port,
        })
    }

    fn build_classpath(java_dir: &Path) -> Result<String, String> {
        let classes_dir = java_dir.join("target/classes");
        if !classes_dir.exists() {
            return Err(format!(
                "Java classes not found at {}. Run 'mvn compile' first.",
                classes_dir.display()
            ));
        }

        let m2_home = std::env::var("HOME").map_or_else(
            |_| PathBuf::from("/root/.m2/repository"),
            |h| PathBuf::from(h).join(".m2/repository"),
        );

        let mut classpath = classes_dir.to_string_lossy().to_string();

        // Glom all jars from Maven cache (simple approach)
        if let Ok(entries) = std::fs::read_dir(&m2_home) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().is_some_and(|e| e == "jar") {
                    classpath.push(':');
                    classpath.push_str(&path.to_string_lossy());
                }
            }
        }

        Ok(classpath)
    }

    #[must_use]
    pub fn port(&self) -> u16 {
        self.port
    }
}

impl Drop for JavaServer {
    fn drop(&mut self) {
        if let Some(mut child) = self.child.take() {
            let _ = child.kill();
            let _ = child.wait();
        }
    }
}

// ── Docker helpers ──────────────────────────────────────────────────────────

/// Manages Docker Compose services for cross-language tests.
pub struct DockerServices;

impl DockerServices {
    /// Start ZK and Nacos via docker-compose.
    ///
    /// # Errors
    /// Returns an error if docker-compose is not found or fails to start.
    pub fn start_all() -> Result<(), String> {
        let compose = PathBuf::from(WORKSPACE_DIR).join(DOCKER_COMPOSE_FILE);
        let output = Command::new("docker")
            .args(["compose", "-f", &compose.to_string_lossy(), "up", "-d"])
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .map_err(|e| format!("docker compose not found: {e}"))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(format!("docker compose up failed: {stderr}"));
        }

        Self::wait_for_zk(Duration::from_secs(30));
        Self::wait_for_nacos(Duration::from_secs(60));

        Ok(())
    }

    /// Stop all Docker Compose services.
    ///
    /// # Errors
    /// Returns an error if docker-compose fails.
    pub fn stop_all() -> Result<(), String> {
        let compose = PathBuf::from(WORKSPACE_DIR).join(DOCKER_COMPOSE_FILE);
        let output = Command::new("docker")
            .args(["compose", "-f", &compose.to_string_lossy(), "down"])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .output()
            .map_err(|e| format!("docker compose down failed: {e}"))?;

        if !output.status.success() {
            return Err("docker compose down failed".into());
        }
        Ok(())
    }

    fn wait_for_zk(timeout: Duration) -> bool {
        let deadline = Instant::now() + timeout;
        while Instant::now() < deadline {
            if let Ok(output) = Command::new("bash")
                .args(["-c", "echo ruok | nc -w 2 localhost 2181"])
                .output()
            {
                if output.status.success() && output.stdout.starts_with(b"imok") {
                    return true;
                }
            }
            std::thread::sleep(Duration::from_millis(500));
        }
        false
    }

    fn wait_for_nacos(timeout: Duration) -> bool {
        let deadline = Instant::now() + timeout;
        while Instant::now() < deadline {
            if let Ok(output) = Command::new("curl")
                .args(["-sf", "http://localhost:8848/nacos/actuator/health"])
                .output()
            {
                if output.status.success() {
                    return true;
                }
            }
            std::thread::sleep(Duration::from_millis(500));
        }
        false
    }
}

// ── Hex formatting (replaces `hex` crate dependency) ────────────────────────

/// Encode bytes as a hex string (lowercase).
#[must_use]
pub fn hex_encode(bytes: &[u8]) -> String {
    let hex_chars = b"0123456789abcdef";
    let mut result = String::with_capacity(bytes.len() * 2);
    for &byte in bytes {
        result.push(hex_chars[(byte >> 4) as usize] as char);
        result.push(hex_chars[(byte & 0xf) as usize] as char);
    }
    result
}

// ── Test utilities ──────────────────────────────────────────────────────────

/// Compare two byte slices with a hex diff on mismatch.
///
/// # Errors
///
/// Returns `Err` with a hex diff if the byte slices differ.
pub fn assert_bytes_eq(expected: &[u8], actual: &[u8], context: &str) -> Result<(), String> {
    if expected == actual {
        return Ok(());
    }

    let mut msg = format!("bytes mismatch ({context}):\n");
    let _ = writeln!(msg, "  expected ({} bytes):", expected.len());
    let _ = writeln!(msg, "    {}", hex_encode(expected));
    let _ = writeln!(msg, "  actual   ({} bytes):", actual.len());
    let _ = writeln!(msg, "    {}", hex_encode(actual));

    let min_len = expected.len().min(actual.len());
    for i in 0..min_len {
        if expected[i] != actual[i] {
            let _ = writeln!(
                msg,
                "  first diff at offset {i}: expected 0x{exp:02x}, actual 0x{act:02x}",
                exp = expected[i],
                act = actual[i]
            );
            break;
        }
    }
    if expected.len() != actual.len() {
        let _ = writeln!(
            msg,
            "  length mismatch: expected {}, actual {}",
            expected.len(),
            actual.len()
        );
    }

    Err(msg)
}
